joints: {
  joint_1: {id: 1, neutral: 205,max_angle: 180,min_angle: -180,max_speed: 90},
  joint_2: {id: 2, max_angle: 90,min_angle: 0,max_speed: 90},
  joint_5: {id: 3, max_angle: 90,min_angle: 0,max_speed: 90},  
}
controllers: {
  arm_controller: {type: follow_controller, joints: [joint_1,joint_2,joint_5], action_name: arm_controller/follow_joint_trajectory,onboard: False }
   }